config/routes.rb
MyHangman::Application.routes.draw do
  devise_for :users

  resources :message
  resources :game
  match '/:id/giveup' => 'game#give_up', :as => :give_up
  match '/games' => 'game#my_games', :as => :my_games
  match '/challenge' => 'game#challenge', :as => :challenge
  root to: "application#index"

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  belongs_to :creator
  attr_accessible :guesses, :word, :wrong_guesses, :user_id, :gameover, :player_id

  def guess(letter)
    error_check(letter)
    if false_guess(letter)
      raise ArgumentError
    end
    if (word.include? letter.downcase) || (word.include? letter.upcase)
      self.guesses+=letter.downcase
    else
      self.wrong_guesses+=letter.downcase
    end
    self.save
    return true
  end

  def word_with_guesses()
    w = word
    if self.gameover
      return w
    end
    w.split("").each do |letter|
      if !(guesses.include? letter) && !(guesses.upcase.include? letter) && !(" \n\"\.\,\'\-\?\!".include? letter)
        w = w.gsub(letter, "-")
      end
    end
    return w
  end

  def check_win_or_lose()
    if wrong_guesses.length == 7
      self.gameover = true
      return :lose
    elsif word_with_guesses == word
      self.gameover = true
      self.save
      return :win
    else
      return :play
    end
  end
  def false_guess(letter)
    if (guesses.include? letter.downcase) || (wrong_guesses.include? letter.downcase)
      return true
    end
  end

  def error_check(letter)
    if letter == nil || letter =~ /[^a-zA-Z]/ || letter == ''
	raise ArgumentError
    end
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
  attr_accessible :text, :type
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def index
  end

end

app/controllers/game_controller.rb
class GameController < ApplicationController
  before_filter :authenticate_user!
  def new
  end

  def challenge
  end

  def create
    if params[:user]
      user = User.find_by_email(params[:user])
      if !user
        flash[:warning] = "Please enter an existing user."
        return redirect_to challenge_path
      end
    end
    game = Game.create(params[:game])
    game.user_id = current_user.id
    game.guesses = ""
    game.wrong_guesses = ""
    game.gameover = false
    ### Will change to challenged player if player exists
    game.player_id = if user then user.id else current_user.id end
    game.save
    if user
      return redirect_to my_games_path
    else
      return redirect_to game_path(game.id)
    end
  end

  def show
    @id = params[:id]
    @game = Game.find(params[:id])
    @gameover = @game.gameover || false
    @word = @game.word_with_guesses
    @wrong_guesses = @game.wrong_guesses
    @remaining = 7 - @wrong_guesses.length
  end

  def update
    game = Game.find(params[:id])
    begin
      game.guess(params[:guess])
      check = game.check_win_or_lose
      if check == :win
        flash[:notice] = "You win!"
      elsif check == :lose
        flash[:warning] = "You lose!"
      end
      redirect_to game_path(game.id)
    rescue ArgumentError
      flash[:warning] = "Please enter appropriate guess."
      redirect_to game_path(game.id)
    end
  end

  def give_up
    game = Game.find(params[:id])
    game.gameover = true
    game.save
    flash[:warning] = "You gave up."
    redirect_to game_path(params[:id])
  end

  def my_games
    @games = current_user.my_games
    @challenges = current_user.my_challenges
    @completed_games = current_user.my_completed_games
    @completed_challenges = current_user.my_completed_challenges
  end
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/views/application/challenge.html.haml
-#  This file is app/views/application/challenge.html.haml

%h1 Challenge Another Player

%div{:id => "board"}
  = form_tag game_index_path do
    = label :user, :email, 'User:', :class => "text"
    = text_field_tag "user", ""
    %br
    = label :game, :word, 'Answer:', :class => "text"
    %br
    = text_area :game, :word, :rows => 5
    %br
    = submit_tag 'Challenge', :class => "btn"

app/views/application/index.html.haml
-#  This file is app/views/application/index.html.haml

%h1 Welcome!

%div{:id => "board"}
  = button_to 'New Game', new_game_path, :class => 'btn', :method => :get
  %br
  %br
  = button_to 'New Challenge', challenge_path, :class => 'btn', :method => :get

app/views/game/my_games.html.haml
-#  This file is app/views/application/my_games.html.haml

%div{:class => "card"}
  %h3 Games
  %table{:id => "list", width: "100%"}
    %thead
      %tr
        %th Game
        %th Challenged By
      %tbody
      - @games.each do |game|
      - challenger = User.find(game.user_id)
        %tr
          %td= link_to "#{game.word_with_guesses}", game_path(game.id)
          %td= if challenger then "#{challenger.email}" else "None" end

%div{:class => "card"}
  %h3 Challenges
  %table{:id => "list", width: "100%"}
    %thead
      %tr
        %th Game
        %th Player
      %tbody
      - @challenges.each do |game|
      - player = User.find(game.player_id)
        %tr
          %td= game.word
          %td= if player then "#{player.email}" else "None" end

%div{:class => "card"}
  %h3 Completed Games
  %table{:id => "list", width: "100%"}
    %thead
      %tr
        %th Game
        %th Challenged By
      %tbody
      - @completed_games.each do |game|
      - challenger = User.find(game.user_id)
        %tr
          %td= link_to "#{game.word_with_guesses}", game_path(game.id)
          %td= if challenger then "#{challenger.email}" else "None" end

%div{:class => "card"}
  %h3 Completed Challenges
  %table{:id => "list", width: "100%"}
    %thead
      %tr
        %th Game
        %th Player
      %tbody
      - @completed_challenges.each do |game|
      - player = User.find(game.player_id)
        %tr
          %td= game.word
          %td= if player then "#{player.email}" else "None" end

app/views/game/new.html.haml
-#  This file is app/views/game/new.html.haml

%h1 Make a New Game
%div{:id => "board"}
  = form_tag game_index_path do

    = label :game, :word, 'Answer:', :class => "text"
    %br
    = text_area :game, :word, :rows => 5
    %br
    = submit_tag 'Start', :class => "btn"

app/views/game/show.html.haml
-#  This file is app/views/game/show.html.haml

%h1 Play the Game

%div{:id => "board"}
  %p{:id => "word"}= @word

  -if !@gameover
    %p{:id => "guesses"}= "Incorrect Guesses: #{@wrong_guesses}"
    %p{:id => "remaining"}= "#{@remaining} left"

    = form_tag game_path(@id), :method => :put do
      = text_field_tag "guess", ""
      = submit_tag "Submit", :class => "btn"
    %br
    = button_to 'Surrender', give_up_path, :class => 'btn', :method => :get

  -else
    = button_to 'New Game', new_game_path, :class => 'btn', :method => :get

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Hangman
    = stylesheet_link_tag 'application'

  %body
    %div{:id=>"container"}
      %div{:id=>"sidebar"} 
        %div{:id => "sidebarLinks"}
          = link_to 'Home', root_path
          %br
          - if user_signed_in?
            = link_to "#{current_user.email}", edit_user_registration_path
            %br
            = link_to "Games", my_games_path
            %br
            %br
            = link_to "Logout", destroy_user_session_path, :method => :delete
          - else
            = link_to "Signup", new_user_registration_path
            %br
            = link_to " Login", new_user_session_path
      #main
        - if flash[:notice]
          #notice.message= flash[:notice]
        - elsif flash[:warning]
          #warning.message= flash[:warning]
        - elsif flash[:alert]
          #alert.message= flash[:alert]
  
        = yield